'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Paintbrush, Check, Loader2, Sparkles } from 'lucide-react';

interface ArtStyle {
  id: string;
  name: string;
  description: string;
  prompt: string;
}

interface StyleSelectorProps {
  selectedStyleId: string | null;
  onSelectStyle: (styleId: string) => void;
  onGenerateImages: (styleId: string, count: number) => void;
  isGenerating: boolean;
}

const STYLE_PREVIEWS: Record<string, string> = {
  watercolor: '🎨',
  pixar: '✨',
  cartoon: '🌈',
  storybook: '📖',
  whimsical: '🦋',
};

export function StyleSelector({
  selectedStyleId,
  onSelectStyle,
  onGenerateImages,
  isGenerating,
}: StyleSelectorProps) {
  const [styles, setStyles] = useState<ArtStyle[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [imageCount, setImageCount] = useState(3);

  useEffect(() => {
    const fetchStyles = async () => {
      try {
        const response = await fetch('/api/art-styles');
        const data = await response.json();
        setStyles(data.styles || []);
      } catch (error) {
        console.error('Error fetching styles:', error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchStyles();
  }, []);

  const handleGenerate = (styleId: string) => {
    onSelectStyle(styleId);
    onGenerateImages(styleId, imageCount);
    setIsOpen(false);
  };

  const selectedStyle = styles.find((s) => s.id === selectedStyleId);

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          size="lg"
          disabled={isGenerating}
          className="bg-white border-2 border-peach-300 hover:border-peach-400 hover:bg-peach-50 text-peach-700"
        >
          {isGenerating ? (
            <>
              <Loader2 className="h-5 w-5 mr-2 animate-spin" />
              Creating Illustrations...
            </>
          ) : (
            <>
              <Paintbrush className="h-5 w-5 mr-2" />
              {selectedStyle ? `Illustrate with ${selectedStyle.name}` : 'Add Illustrations'}
            </>
          )}
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl font-playfair text-lavender-900">
            Choose an Art Style
          </DialogTitle>
          <DialogDescription>
            Select a style to bring your story to life with beautiful illustrations
          </DialogDescription>
        </DialogHeader>

        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-8 w-8 animate-spin text-lavender-500" />
          </div>
        ) : (
          <div className="space-y-6 mt-4">
            {/* Image Count Selector */}
            <div className="bg-lavender-50 rounded-xl p-4">
              <label className="text-sm font-medium text-lavender-700 mb-2 block">
                Number of illustrations
              </label>
              <div className="flex gap-2">
                {[2, 3, 4, 5].map((num) => (
                  <button
                    key={num}
                    onClick={() => setImageCount(num)}
                    className={`
                      px-4 py-2 rounded-lg font-medium transition-all
                      ${imageCount === num
                        ? 'bg-lavender-600 text-white'
                        : 'bg-white text-lavender-600 border border-lavender-200 hover:border-lavender-400'
                      }
                    `}
                  >
                    {num}
                  </button>
                ))}
              </div>
              <p className="text-xs text-lavender-500 mt-2">
                More illustrations = longer generation time
              </p>
            </div>

            {/* Style Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {styles.map((style) => (
                <StyleCard
                  key={style.id}
                  style={style}
                  isSelected={selectedStyleId === style.id}
                  onSelect={() => handleGenerate(style.id)}
                  emoji={STYLE_PREVIEWS[style.id] || '🖼️'}
                />
              ))}
            </div>

            <p className="text-center text-sm text-lavender-500">
              <Sparkles className="h-4 w-4 inline mr-1" />
              Each illustration is uniquely generated by AI
            </p>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

interface StyleCardProps {
  style: ArtStyle;
  isSelected: boolean;
  onSelect: () => void;
  emoji: string;
}

function StyleCard({ style, isSelected, onSelect, emoji }: StyleCardProps) {
  return (
    <button
      onClick={onSelect}
      className={`
        relative p-4 rounded-xl border-2 text-left transition-all
        ${isSelected
          ? 'border-peach-500 bg-peach-50 shadow-md'
          : 'border-gray-200 bg-white hover:border-peach-300'
        }
      `}
    >
      {isSelected && (
        <div className="absolute top-2 right-2 h-5 w-5 bg-peach-500 rounded-full flex items-center justify-center">
          <Check className="h-3 w-3 text-white" />
        </div>
      )}

      <div className="flex items-start gap-3">
        <div className="text-3xl">{emoji}</div>

        <div className="flex-1 min-w-0">
          <h4 className="font-semibold text-lavender-900">{style.name}</h4>
          <p className="text-sm text-lavender-600">{style.description}</p>
        </div>
      </div>
    </button>
  );
}
